### PR TITLE
BUG: Remove wrong Python wrap file.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Remove Python wrap file accidentally committed in 6c736b7.

### CODE REVIEW

**Comment by thewtex** [comment]
@jhlegarreta I enabled the CI services for this repository. Please try re-pushing this branch to trigger the builds with something like

```
git checkout RemoveWrongWrapFile
git commit --amend --no-edit
git push -f origin HEAD
```

**Comment by jhlegarreta** [comment]
Done.

**Comment by thewtex** [comment]
Thanks @jhlegarreta .

I fixed the CircleCI build configuration so it builds forked pull requests.

Other CI errors are unrelated, so merging.

**Comment by jhlegarreta** [comment]
Thanks @thewtex  !

**Pull request merged**
