### PR TITLE
DOC: Add `README.rst` file.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add a `README.rst` file to the remote module repository with basic module
information, a reference to the `LICENSE` file, and CI status badges.

### CODE REVIEW

**Comment by dzenanz** [comment]
I guess this should be merged after the CI PR #4.

**Comment by jhlegarreta** [comment]
Yes, I'll rebase on master once #4 gets merged. Thanks.

**Comment by dzenanz** [comment]
It does not need to be rebased, just merged after.

**Comment by dzenanz** [comment]
@thewtex maybe that key needs to be added to enable CI?

**Pull request merged**
